apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go App
        uses: docker://golang:1.20
        run: |
          go build -v ./...
      - name: Run tests
        uses: docker://golang:1.20
        run: |
          go test -v ./...
      - name: docker login
        id: docker-login-step
        uses: docker://alpine:3.17
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
          cat << EOF > "$CLOUDBEES_OUTPUTS/dockerconfigjson"
          {
              "auths": {
                  "https://index.docker.io/v1/": {
                      "username": "${DOCKER_USERNAME}"",
                      "password": "${DOCKER_PASSWORD}",
                      "auth": "${AUTH}"
                  }
              }
          }
          EOF
      - name: Log in to OCI registry
        uses: cloudbees-io/configure-oci-credentials@v0
        with:
          registry: index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to OCI Registry
        uses: cloudbees-io/kaniko@v1
        with:
          dockerconfigjson: ${{ steps.docker-login-step.outputs.dockerconfigjson }}
          dockerfile: ./Dockerfile
          destination: index.docker.io/swashbuck1r/sample-go-app:latest
          context: .


  