apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go App
        uses: docker://golang:1.20
        run: |
          go build -v ./...
      - name: Run tests
        uses: docker://golang:1.20
        run: |
          go test -v ./...
      - name: Log in to OCI registry
        uses: cloudbees-io/configure-oci-credentials@v0
        with:
          registry: index.docker.io/v2/swashbuck1r
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: debug
        uses: docker://golang:1.20
        run: |
          echo "debugging: $HOME"
          ls -al $HOME
          cat $HOME/.docker/config.json
      - name: Push image to OCI Registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: index.docker.io/swashbuck1r/simple-go-api-server:1.0.4

  